# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import video_engine_pb2 as video__engine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in video_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecutePlan = channel.unary_stream(
                '/video_core.EngineController/ExecutePlan',
                request_serializer=video__engine__pb2.CorrectionPlan.SerializeToString,
                response_deserializer=video__engine__pb2.ExecutionProgress.FromString,
                _registered_method=True)


class EngineControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecutePlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecutePlan': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecutePlan,
                    request_deserializer=video__engine__pb2.CorrectionPlan.FromString,
                    response_serializer=video__engine__pb2.ExecutionProgress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video_core.EngineController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('video_core.EngineController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EngineController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecutePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/video_core.EngineController/ExecutePlan',
            video__engine__pb2.CorrectionPlan.SerializeToString,
            video__engine__pb2.ExecutionProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
