# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'video_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12video_engine.proto\x12\nvideo_core\"\xc8\x01\n\x07\x43ommand\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.video_core.CommandType\x12\x15\n\rstart_time_ms\x18\x02 \x01(\x05\x12\x13\n\x0b\x65nd_time_ms\x18\x03 \x01(\x05\x12\x37\n\nparameters\x18\x04 \x03(\x0b\x32#.video_core.Command.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"l\n\x0e\x43orrectionPlan\x12\x18\n\x10input_video_path\x18\x01 \x01(\t\x12\x19\n\x11output_video_path\x18\x02 \x01(\t\x12%\n\x08\x63ommands\x18\x03 \x03(\x0b\x32\x13.video_core.Command\"\x85\x01\n\x11\x45xecutionProgress\x12\x1b\n\x13progress_percentage\x18\x01 \x01(\x05\x12\x14\n\x0c\x63urrent_task\x18\x02 \x01(\t\x12\x13\n\x0bis_finished\x18\x03 \x01(\x08\x12\x11\n\thas_error\x18\x04 \x01(\x08\x12\x15\n\rerror_details\x18\x05 \x01(\t*`\n\x0b\x43ommandType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0b\x43UT_SEGMENT\x10\x01\x12\r\n\tSTABILIZE\x10\x02\x12\x11\n\rCOLOR_CORRECT\x10\x03\x12\x11\n\rAUDIO_DENOISE\x10\x04\x32^\n\x10\x45ngineController\x12J\n\x0b\x45xecutePlan\x12\x1a.video_core.CorrectionPlan\x1a\x1d.video_core.ExecutionProgress0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND_PARAMETERSENTRY']._loaded_options = None
  _globals['_COMMAND_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_COMMANDTYPE']._serialized_start=483
  _globals['_COMMANDTYPE']._serialized_end=579
  _globals['_COMMAND']._serialized_start=35
  _globals['_COMMAND']._serialized_end=235
  _globals['_COMMAND_PARAMETERSENTRY']._serialized_start=186
  _globals['_COMMAND_PARAMETERSENTRY']._serialized_end=235
  _globals['_CORRECTIONPLAN']._serialized_start=237
  _globals['_CORRECTIONPLAN']._serialized_end=345
  _globals['_EXECUTIONPROGRESS']._serialized_start=348
  _globals['_EXECUTIONPROGRESS']._serialized_end=481
  _globals['_ENGINECONTROLLER']._serialized_start=581
  _globals['_ENGINECONTROLLER']._serialized_end=675
# @@protoc_insertion_point(module_scope)
